### ISSUE TITLE
Add strava

### ISSUE THREAD

**Issue by jbelien** [osmbe/historical-map#1]
From @StevenClays (#4):
> Strava heatmap is up and running again, so is it possible to add this to play.osm.be/historischekaart.html as an overlay?
https://anygis.ru/api/v1/Tracks_Strava_All_HD/{$x}/{$y}/{$z}

**Comment by joostschouppe** [comment]
Closing for now. Feel free to re-open if you have a good solution to add Strava here. No idea how to implement the JOSM solution here, and it's not an ideal solution anyway.
